### ISSUE TITLE
UNIONとUNION ALLの使い分け

### ISSUE THREAD

**Issue by mtakahashi-kts** [okitahiro/study_marking_201503#6]
@521e4000b5d20523ca5890a355d1c504c2e535e0
UNION: 重複行を削除
UNION ALL: 重複行も削除せずに取得
1-1や1-2の場合は重複することがないので、ALLは不要かと思います

[参考](http://www.dbonline.jp/mysql/select/index18.html)

**Comment by okitahiro** [comment]
UNIONでは二つの集合をマージした後、重複行を排除するためのソートが発生します。
そのため、行の重複を気にしなくていい場合や、あらかじめ重複が発生しないことが明白な場合は、
無駄なソート処理を発生させないUNION ALLを使用したほうがパフォーマンス的に優れているかと思います。

以上の理由により、今回はUNION ALLを使用させていただきました。

**Comment by mtakahashi-kts** [comment]
了解しました。修正不要です
